### ISSUE TITLE
Problem with reproducing results

### ISSUE THREAD

**Issue by Baidi96** [bedapudi6788/deeppunct#1]
Hi, I read your post [https://medium.com/@praneethbedapudi/deepcorrection-3-spell-correction-and-simple-grammar-correction-d033a52bc11d](url) and I am trying this pertained model with deeppunct_params_en and deeppunct_checkpoint_google_news/ deeppunct_checkpoint_tatoeba_cornell/ deeppunct_checkpoint_wikipedia respectively, however instead of getting:

> INPUT: iwill be there four u
> OUTPUT: I will be there for you.

I got:
>INPUT: iwill be there four u
>OUTPUT: Iwill be there four ?

Any suggestion to get result as good as yours?

**Comment by bedapudi6788** [comment]
Hi @Baidi96 my bad! I forgot to upload the pre-trained models for DeepCorrection3 post. The models in the link are for deeppunct. I think I have these stored somwhere in my drive. I will check and get back to you.

**Comment by SrilakshmiGodugunuri27** [comment]
Hello @Baidi96  can you help me how to run https://github.com/bedapudi6788/deeppunct ?

**Comment by SrilakshmiGodugunuri27** [comment]
Hi @bedapudi6788  can you please help me with training and testing data sets links?

**Comment by bedapudi6788** [comment]
@SrilakshmiG1 I hope your questions are answered with the examples I added, please contact me if you need any more help.

**Comment by bedapudi6788** [comment]
@Baidi96 I am currently re-training the grammar-correction model on the same data and will upload the checkpoints for that. Keeping this issue open till then.

**Comment by jgoodrich77** [comment]
Question about the character limits you mention at 200; would this repo be a good starting point to help 'normalize,' for lack of a better term, the grammar in a ~13 megabyte text file?

**Comment by Mozen** [comment]
@Baidi96 I got the same result with you。 @bedapudi6788  do you upload the new pre-trained models?

**Comment by Mozen** [comment]
@bedapudi6788 can you give  train data? I want train it myself but  I can't find google news dataset。thinks

**Comment by i141631** [comment]
> Hi @bedapudi6788 model you gave in links is for punctuation so please upload the latest model

**Comment by bedapudi6788** [comment]
@i141631 @Baidi96 @Mozen 

https://drive.google.com/open?id=1O4x8rwGJAh8gRo8sjm0kuKFf6vCEm93G

I lost the original checkpoint and params. I re-trained a similar model and you can find the checkpoints for that above. Please note that you will need to install the latest version of txt2txt to use these.

```
pip install --upgrade txt2txt
```

```
from txt2txt import build_model, infer

model, params = build_model(params_path='params', enc_lstm_units=256)

model.load_weights('checkpoint')

while 1:
    print('Enter input')
    print(infer(input(), model, params))
```

**Comment by JeffSaa** [comment]
Hi @bedapudi6788, this project is awesome.

`corrector = DeepCorrect('Downloads/spellcorrection_checkpoints_new/params', 'Downloads/spellcorrection_checkpoints_new/checkpoint')`

produce this error
`Total params: 874,151
Trainable params: 874,151
Non-trainable params: 0
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/deepcorrect/deepcorrect.py", line 9, in __init__
    DeepCorrect.deepcorrect_model[0].load_weights(checkpoint_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/engine/saving.py", line 1056, in load_weights_from_hdf5_group
    ' elements.')
ValueError: Layer #1 (named "embedding_11" in the current model) was found to correspond to layer bidirectional_1 in the save file. However the new layer embedding_11 expects 1 weights, but the saved weights have 6 elements.`

**Comment by JeffSaa** [comment]
This spellcorrection_checkpoints_new is the model described on https://medium.com/@praneethbedapudi/deepcorrection-3-spell-correction-and-simple-grammar-correction-d033a52bc11d?

How can I train a new model?
Also can you upload the training data? I want to increase it and re-train...

**Comment by JeffSaa** [comment]
> @i141631 @Baidi96 @Mozen
> 
> https://drive.google.com/open?id=1O4x8rwGJAh8gRo8sjm0kuKFf6vCEm93G
> 
> I lost the original checkpoint and params. I re-trained a similar model and you can find the checkpoints for that above. Please note that you will need to install the latest version of txt2txt to use these.
> 
> ```
> pip install --upgrade txt2txt
> ```
> 
> ```
> from txt2txt import build_model, infer
> 
> model, params = build_model(params_path='params', enc_lstm_units=256)
> 
> model.load_weights('checkpoint')
> 
> while 1:
>     print('Enter input')
>     print(infer(input(), model, params))
> ```

`infer('how is you', model, params)`

show as output:

`[[{'sequence': 'how is you', 'prob': 0.9629635300093986}, {'sequence': 'how are you', 'prob': 0.010747020403238734}, {'sequence': 'how was you', 'prob': 0.007674736297337538}]]`

Is correct? the first is always the same input?

**Comment by bedapudi6788** [comment]
@JeffSaa 
> This spellcorrection_checkpoints_new is the model described on https://medium.com/@praneethbedapudi/deepcorrection-3-spell-correction-and-simple-grammar-correction-d033a52bc11d?

yes, it is more or less the same one described in there.

> Also can you upload the training data? I want to increase it and re-train...

Like i explained in the blog, the training data is auto generated. 

> Is correct? the first is always the same input?

No, the outputs are ordered based on their probabilities. In the example you used, the model didn't make any changes to the input sentence.

For example, see the following

```
infer('did you had lunch', model, params)

[[{'sequence': 'did you have lunch', 'prob': 0.6140889177749181}, {'sequence': 'did you had lunch', 'prob': 0.10453944401814}, {'sequence': 'did you head lunch', 'prob': 0.07858789175125618}]]
```

**Comment by JeffSaa** [comment]
What do you mean with auto-generated data?

I'm refearing to 

> I built a clean text corpus of roughly 80 million sentences

and

> Planning to expand on this, I created a correction dataset by introducing homonym, homophone and common grammatical errors. Since I already exhausted my resources for training the spell correction model, I was only able to train the model on data generated from 1.4 million sentences (Tatoeba + Cornell movie lines) for 5 hours.

I need this project for an university's project. But I need to improve this cases that I told you in my previous comment. So, can you explain me how to train a new model and how can I get the training data? I need to detect grammar error and tell what kind of error are... can this project help me?

**Comment by bedapudi6788** [comment]
> I built a clean text corpus of roughly 80 million sentences

these are clean sentences. you can get lot of clean sentences from lot of places (wikipedia, tatoeba, google news corpus etc.)

> I created a correction dataset by introducing homonym, homophone and common grammatical errors.

This is what I meant by "generated data". You have to write your own generator (to introduce the type of errors you want) for this.

**Comment by JeffSaa** [comment]
Ohh ok I understood now. Can you explain me how train my own model? and if is possible to get the error type?

**Comment by bedapudi6788** [comment]
For training this take a look at https://github.com/bedapudi6788/txt2txt/ 

Since this repo doesn't support getting the error type I cannot help you very much there.

**Comment by JeffSaa** [comment]
Ok. Thanks

**Comment by i141631** [comment]
ValueError: Layer #1 (named "embedding_5" in the current model) was found to correspond to layer bidirectional_1 in the save file. However the new layer embedding_5 expects 1 weights, but the saved weights have 6 elements.
while loading new checkpoints

**Comment by bedapudi6788** [comment]
@i141631 please provide the sample code you used and the output of ```pip show txt2txt```

**Comment by i141631** [comment]
Collecting txt2txt
  Downloading https://files.pythonhosted.org/packages/25/ef/9855f64929007b39880a25581808f8b6cd714629da350a9643e8a97af089/txt2txt-1.1.1-py2.py3-none-any.whl
Requirement already up-to-date: keras>=2.2.0 in ./lib/python3.6/site-packages (from txt2txt)
Requirement already up-to-date: numpy in ./lib/python3.6/site-packages (from txt2txt)
Requirement already up-to-date: keras-applications>=1.0.6 in ./lib/python3.6/site-packages (from keras>=2.2.0->txt2txt)
Requirement already up-to-date: pyyaml in ./lib/python3.6/site-packages (from keras>=2.2.0->txt2txt)
Requirement already up-to-date: h5py in ./lib/python3.6/site-packages (from keras>=2.2.0->txt2txt)
Requirement already up-to-date: keras-preprocessing>=1.0.5 in ./lib/python3.6/site-packages (from keras>=2.2.0->txt2txt)
Requirement already up-to-date: six>=1.9.0 in ./lib/python3.6/site-packages (from keras>=2.2.0->txt2txt)
Requirement already up-to-date: scipy>=0.14 in ./lib/python3.6/site-packages (from keras>=2.2.0->txt2txt)
Installing collected packages: txt2txt
  Found existing installation: txt2txt 1.0.9
    Uninstalling txt2txt-1.0.9:
      Successfully uninstalled txt2txt-1.0.9
Successfully installed txt2txt-1.1.1
Note: you may need to restart the kernel to use updated packages.



from txt2txt import build_model, infer

model, params = build_model(params_path='/home/waleed/deepcorrect-master/spellcorrection_checkpoints_new/params', enc_lstm_units=256)

model.load_weights('/home/waleed/deepcorrect-master/spellcorrection_checkpoints_new/checkpoint')

while 1:
    print('Enter input')
    print(infer(input(), model, params))

**Comment by bedapudi6788** [comment]
>  Note: you may need to restart the kernel to use updated packages.

like it said, did you restart the kernel?

**Comment by i141631** [comment]
why capital letter not working 

print(infer('Why th hel', model, params))
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-9928dd083e76> in <module>
----> 1 print(infer('Why th hel', model, params))

~/deepcorrect-master/lib/python3.6/site-packages/txt2txt/txt2txt.py in infer(texts, model, params, beam_size, max_beams, min_cut_off_len, cut_off_ratio)
    130     max_output_length = params['max_output_length']
    131 
--> 132     all_decoder_outputs = generate(texts, input_encoding_dict, model, max_input_length, max_output_length, beam_size, max_beams, min_cut_off_len, cut_off_ratio)
    133     outputs = []
    134 

~/deepcorrect-master/lib/python3.6/site-packages/txt2txt/txt2txt.py in generate(texts, input_encoding_dict, model, max_input_length, max_output_length, beam_size, max_beams, min_cut_off_len, cut_off_ratio)
     83 
     84 
---> 85         batch_encoder_input = encode_sequences(input_encoding_dict, batch_encoder_input, max_input_length)
     86         batch_decoder_input = np.asarray(batch_decoder_input)
     87         batch_predictions = model.predict([batch_encoder_input, batch_decoder_input])

~/deepcorrect-master/lib/python3.6/site-packages/txt2txt/txt2txt.py in encode_sequences(encoding_dict, sequences, max_length)
     37     for i in range(len(sequences)):
     38         for j in range(min(len(sequences[i]), max_length)):
---> 39             encoded_data[i][j] = encoding_dict[sequences[i][j]]
     40     return encoded_data
     41 

KeyError: 'W'

**Comment by bedapudi6788** [comment]
@i141631 only lower case alphabet is supported as input. see the params file to understand.

**Comment by i141631** [comment]
if you are correcting punctuation then isn't it wrong to cater only lower case input

**Comment by bedapudi6788** [comment]
@i141631 unlike https://github.com/bedapudi6788/deepsegment, deepcorrect is meant as more of a experimental repo. You will have to fine-tune/ re-train using https://github.com/bedapudi6788/txt2txt/ for your use cases.

**Comment by i141631** [comment]
how you made data can you share code for preparing data

**Comment by maloyan** [comment]
Hello, I want to train to get a model for russian language. Can you please describe how the training data should look like, how big should it be and what's your recommended parameters for model.fit()

Thanks in advance

**Comment by bedapudi6788** [comment]
@maloyan https://github.com/bedapudi6788/txt2txt/ see the readme.

**Comment by bedapudi6788** [comment]
we are working on a faster and more accurate punctuation correction at https://github.com/notAI-tech/fastpunct . 

The core idea is similar (seq2seq), but @harikodali figured out a way to make the decoding faster. This repo is expected to be released by the end of this month.
