### ISSUE TITLE
ValueError: Dimension 0 in both shapes must be equal, but are 2 and 98. Shapes are [2,256] and [98,256]. for 'Assign_1' (op: 'Assign') with input shapes: [2,256], [98,256].

### ISSUE THREAD

**Issue by svisavalia** [bedapudi6788/deeppunct#16]
Once I write the same code as mentioned, I am getting above mentioned error.

How to go ahead?

**Comment by bedapudi6788** [comment]
verify if txt2txt's verison is 1.0.9

**Comment by svisavalia** [comment]
I have installed txt2txt using "pip install txt2txt==1.0.9" then also error is same.

**Comment by bedapudi6788** [comment]
can you reproduce the error in a colab notebook? https://colab.research.google.com/drive/1hWCUieBz1nJaT_s2vWH1AgjqfljUc_jU This is a notebook I made 3 days ago. Take a look at it for reference.

**Comment by svisavalia** [comment]
No error using above provided notebook. I was using pre trained model "deeppunct_checkpoint_google_news". The code you have provided works for me. Thank you so much.
