### ISSUE TITLE
input shape error 

### ISSUE THREAD

**Issue by surianmau** [bedapudi6788/deeppunct#21]
1608   except errors.InvalidArgumentError as e:
   1609     # Convert to ValueError for backwards compatibility.
-> 1610     raise ValueError(str(e))
   1611 
   1612   return c_op

ValueError: Dimension 0 in both shapes must be equal, but are 2 and 98. Shapes are [2,256] and [98,256]. for 'Assign' (op: 'Assign') with input shapes: [2,256], [98,256].

**Comment by bedapudi6788** [comment]
https://github.com/bedapudi6788/deepcorrect/issues/16
