### ISSUE TITLE
sentence is not punctuated properly

### ISSUE THREAD

**Issue by ghost** [bedapudi6788/deeppunct#22]
when i 

from deepcorrect import DeepCorrect

corrector = DeepCorrect(deeppunct_params_en, deeppunct_checkpoint_tatoeba_cornell)

corrector.correct('hey')

it is giving me "hey."

and when i

corrector.correct('hello how are you what is your name')

it gives me 'Hello, how are you what is your name.'

no question marks , why?.

please help me what should i do?

**Comment by bedapudi6788** [comment]
we are working on a faster and more accurate punctuation correction at https://github.com/notAI-tech/fastpunct .

The core idea is similar (seq2seq), but @harikodali figured out a way to make the decoding faster. This repo is expected to be released by the end of this month.
