### ISSUE TITLE
Problem with checkpoint_path

### ISSUE THREAD

**Issue by DGV1995** [bedapudi6788/deeppunct#3]
Hi, 

I am getting the following error: 'OSError: Unable to open file (unable to open file: name = 'checkpoint_path', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)'

Do you know how to fix it?

Kind regards!

**Comment by bedapudi6788** [comment]
checkpoint_path is a placeholder. download the pre-trained model and pass the path.
