### ISSUE TITLE
Error in running the example.

### ISSUE THREAD

**Issue by chinmaydas96** [bedapudi6788/deeppunct#5]
After installing the TensorFlow version 1.14.0  and deepcorrect, I am running the example.
But I am getting the following error.

>ValueError: Dimension 0 in both shapes must be equal, but are 2 and 98. Shapes are [2,256] and [98,256]. for 'Assign' (op: 'Assign') with input shapes: [2,256], [98,256].

**Comment by bedapudi6788** [comment]
Did you install txt2txt separately? DeepCorrect works with txt2txt==1.0.9 . Latest versions of txt2txt does not support deepcorrect.

**Comment by chinmaydas96** [comment]
Yes, I did install txt2txt  separately.

**Comment by chinmaydas96** [comment]
what would be the params_path ?

**Comment by bedapudi6788** [comment]
https://github.com/bedapudi6788/deepcorrect/issues/2#issuecomment-487835029

**Comment by sumitsharma14k** [comment]
I did **pip3 install deepcorrect**

Collecting deepcorrect
  Using cached https://files.pythonhosted.org/packages/17/25/e131f4ee1b2c2077613d5d764bfc88d0e0330523746a0aafb21ed712f06d/deepcorrect-1.0.5-py2.py3-none-any.whl
Requirement already satisfied: txt2txt==1.0.9 in /Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages (from deepcorrect) (1.0.9)
Requirement already satisfied: keras>=2.2.0 in /Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages (from txt2txt==1.0.9->deepcorrect) (2.2.4)
Requirement already satisfied: numpy in /Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages (from txt2txt==1.0.9->deepcorrect) (1.17.0)
Requirement already satisfied: six>=1.9.0 in /Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages (from keras>=2.2.0->txt2txt==1.0.9->deepcorrect) (1.12.0)
Requirement already satisfied: pyyaml in /Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages (from keras>=2.2.0->txt2txt==1.0.9->deepcorrect) (5.1.2)
Requirement already satisfied: scipy>=0.14 in /Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages (from keras>=2.2.0->txt2txt==1.0.9->deepcorrect) (1.3.0)
Requirement already satisfied: keras-applications>=1.0.6 in /Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages (from keras>=2.2.0->txt2txt==1.0.9->deepcorrect) (1.0.8)
Requirement already satisfied: h5py in /Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages (from keras>=2.2.0->txt2txt==1.0.9->deepcorrect) (2.9.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages (from keras>=2.2.0->txt2txt==1.0.9->deepcorrect) (1.1.0)
Installing collected packages: deepcorrect
Successfully installed deepcorrect-1.0.5

but still I am getting this issue?

**Comment by chinmaydas96** [comment]
install first then txt2txt  with pip. Should work.

**Comment by bedapudi6788** [comment]
@chinmaydas96 You don't need to separately install txt2txt. As you can see from https://github.com/bedapudi6788/deepcorrect/blob/fb62177e3212323912f3053ae4e34ffdbc4a47c2/setup.py#L25 

it is clearly defined in the requirements and pip will install it for you.

**Comment by bedapudi6788** [comment]
@achintyaha I am 100% confident that you have a newer version of txt2txt installed. The error you got when loading the checkpoint is very very specific and will not happen unless you have txt2txt>1.0.9 installed. 

Can you do ```pip show txt2txt``` and post the output here?

Also, for your reference,

https://colab.research.google.com/drive/1XJVK1N1e44lTxklZZxBsW6FfWBh3Ne04

**Comment by sumitsharma14k** [comment]
**pip show txt2txt**

Name: txt2txt
Version: 1.0.9
Summary: Out of the Box, Easy to use sequence to sequence library with attention for text.
Home-page: https://github.com/bedapudi6788/txt2txt
Author: BEDAPUDI PRANEETH
Author-email: praneethbedapudi@gmail.com
License: GPLv3
Location: /Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages
Requires: numpy, keras
Required-by: deepcorrect

**Comment by bedapudi6788** [comment]
@achintyaha  Are you sure that you are doing all this in the same environment? While installing it looked like you used pip3? is the "pip" you used to run "pip show" the same pip?

**Comment by sumitsharma14k** [comment]
It is same in both cases
**pip3 show txt2txt**

Name: txt2txt
Version: 1.0.9
Summary: Out of the Box, Easy to use sequence to sequence library with attention for text.
Home-page: https://github.com/bedapudi6788/txt2txt
Author: BEDAPUDI PRANEETH
Author-email: praneethbedapudi@gmail.com
License: GPLv3
Location: /Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages
Requires: numpy, keras
Required-by: deepcorrect

**Comment by bedapudi6788** [comment]
Can you do
```
import os
import txt2txt
os.path.abspath(txt2txt.__file__)
```

and post it's output here?

**Comment by sumitsharma14k** [comment]
**python3**

Python 3.7.4 (default, Jul  9 2019, 18:15:00) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import txt2txt
/Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING: Logging before flag parsing goes to stderr.
W0823 18:08:35.914457 4379403712 deprecation_wrapper.py:119] From /Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages/txt2txt/txt2txt.py:8: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

Using TensorFlow backend.
>>> os.path.abspath(txt2txt.__file__)
'/Users/shayana/Downloads/work/speech-venv/lib/python3.7/site-packages/txt2txt/__init__.py'


PS: I am using virtual env. Does that make any difference?

**Comment by bedapudi6788** [comment]
I am not sure why it's using newer version of txt2txt. It's very tough to debug that without having access to the system (might be a number of reasons). As you can see fro the colab notebook I shared, in a clean environment it will work as expected.

Can you just make a new environment and try this once again?

**Comment by sumitsharma14k** [comment]
Okay will try it. I have to again install tensorflow and it will take some time. Will get back to you after that.
Thanks for the help.

**Comment by sumitsharma14k** [comment]
Do I need to install any particular version of tensorflow and other dependencies?

**Comment by bedapudi6788** [comment]
not really. (I tested with 1.8 to 1.14). Also, I am very confident that this is not a tensorflow issue.

**Comment by sumitsharma14k** [comment]
I deleted the virtualenv and did the process on my main system only but still getting the issue.

**pip3 show txt2txt**

Name: txt2txt
Version: 1.0.9
Summary: Out of the Box, Easy to use sequence to sequence library with attention for text.
Home-page: https://github.com/bedapudi6788/txt2txt
Author: BEDAPUDI PRANEETH
Author-email: praneethbedapudi@gmail.com
License: GPLv3
Location: /usr/local/lib/python3.7/site-packages
Requires: keras, numpy
Required-by: deepcorrect

**MacBookAir:~/Downloads/work/speech-venv $ python3**

Python 3.7.4 (default, Jul  9 2019, 18:15:00) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import txt2txt
WARNING: Logging before flag parsing goes to stderr.
W0824 13:30:00.092739 4630320576 deprecation_wrapper.py:119] From /usr/local/lib/python3.7/site-packages/txt2txt/txt2txt.py:8: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

Using TensorFlow backend.
>>> os.path.abspath(txt2txt.__file__)
'/usr/local/lib/python3.7/site-packages/txt2txt/__init__.py'
>>>

**Comment by bedapudi6788** [comment]
can you manually install ```pip3 install txt2txt==1.0.9``` and check again

**Comment by sumitsharma14k** [comment]
Still same issue. Is it possible that this issue is because of some different dependencies mismatch or anything else?

**commands I am using**

>>> from deepcorrect import DeepCorrect
>>> checkpoint_path = "/Users/shayana/Downloads/work/speech-venv/deep-punct/deeppunct_checkpoint_google_news"
>>> params_path = "/Users/shayana/Downloads/work/speech-venv/deep-punct/params_path"
>>> corrector = DeepCorrect(params_path, checkpoint_path)
