### ISSUE TITLE
output the text only

### ISSUE THREAD

**Issue by daniellequijano** [bedapudi6788/deeppunct#6]
from deepcorrect import DeepCorrect

checkpoint_path = "./deep_punct_v2_model/deeppunct_checkpoint_wikipedia"
params_path = "./deep_punct_v2_model/deeppunct_params_en"

corrector = DeepCorrect(params_path, checkpoint_path)
corrector.correct('how are you')

This is my output:
[{'sequence': 'How are you?', 'prob': 0.9735229413488089}]

I only want to print the 'How are you?' without printing the sequence and prob. What should I do?

**Comment by bedapudi6788** [comment]
```
from deepcorrect import DeepCorrect

checkpoint_path = "./deep_punct_v2_model/deeppunct_checkpoint_wikipedia"
params_path = "./deep_punct_v2_model/deeppunct_params_en"

corrector = DeepCorrect(params_path, checkpoint_path)
output = corrector.correct('how are you')[0]['sequence']
```

**Comment by daniellequijano** [comment]
Thank you!!!
