### ISSUE TITLE
Can't reproduce the same result as Demo

### ISSUE THREAD

**Issue by zhushaojin** [bedapudi6788/deeppunct#9]
Hi, I can't reproduce the same result using the code as Demo

The system environment is Python 3.7.3, TensorFlow 1.14.0, txt2txt 1.0.9, 

I used below parameter as it says in README.md, the params and checkpoint are download at https://drive.google.com/open?id=1Yd8cJaqfQkrJMbRVWIWtuyo4obTDYu-e

`def __init__(self, params_path, checkpoint_path):
        DeepCorrect.deepcorrect_model = build_model("./deeppunct_params_en")
        DeepCorrect.deepcorrect_model[0].load_weights("./deeppunct_checkpoint_google_news")`

I tried two sentence, the result comparison is as follow:

**input**: hey
**my output**: [{'sequence': 'Hey?', 'prob': 0.6868892775191712}]
**Demo output**:  "deep-segment_punct": [
    "Hey."
  ]

**input**: 'Why you did this to me I hate you you are dead to me'
**my output**: [{'sequence': 'Why you did this to me I hate you you are dead to me.', 'prob': 0.6264143199088837}]
**Demo output**:  "deep-segment_punct": [
    "Why you did this to me? I hate you, You are dead to me."
  ]

Where could the problem be? How can I get the same result as it in [DeepPunct](http://bpraneeth.com/projects/deeppunct)

If you need more details to locate the error, please tell me.

Thanks

**Comment by bedapudi6788** [comment]
The demo uses deepsegment + deeppunct. Input text is passed through deepsegment and the split sentences are then passed to deeppunct one by one. Also, the decoding strategy is slightly different.

**Comment by zhushaojin** [comment]
@bedapudi6788 Thanks for your replay!
Sorry to bother you again.
I followed your instruction, passed the input through two modules. DeepSeg works fine but DeepPunct faced a "load parameter error"

the code is as follow:

--------------------------------------------------
import sys
from deepsegment import DeepSegment
from deepcorrect import DeepCorrect

input_string = sys.argv[1]
 
segmenter = DeepSegment('en')
seg_string = segmenter.segment(input_string)

corrector = DeepCorrect("./models/deeppunct_params_en", "./models/deeppunct_checkpoint_g    oogle_news")

output = corrector.correct(seg_string[0])

--------------------------------------------------

When inputting parameter "I am Batman I live in Gotham", the code works fine until "corrector = DeepCorrect(' ', ' ')". 

The error report is
`Traceback (most recent call last):
  File "deep_segment_punct.py", line 13, in <module>
    corrector = DeepCorrect('./models/deeppunct_params_en', "./models/deeppunct_checkpoint_google_news")
  File "/Users/zhushaojin/Documents/deepcorrect/main_dir/deepcorrect.py", line 9, in __init__
    DeepCorrect.deepcorrect_model[0].load_weights(checkpoint_path)
  File "//anaconda3/envs/python36/lib/python3.6/site-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "//anaconda3/envs/python36/lib/python3.6/site-packages/keras/engine/saving.py", line 1056, in load_weights_from_hdf5_group
    ' elements.')
ValueError: Layer #1 (named "bidirectional_1" in the current model) was found to correspond to layer embedding_1 in the save file. However the new layer bidirectional_1 expects 6 weights, but the saved weights have 1 elements.`

The models used by DeepCorrect are downloaded in https://drive.google.com/open?id=1Yd8cJaqfQkrJMbRVWIWtuyo4obTDYu-e

I think it might be the problem of the version of TensorFlow version? Since seqtag_keras (required by DeepSegment) needs tensorflow==1.12 while txt2txt(required by Deepcorrect) needs tensorflow==1.8.0

Or am I using the wrong params and checkpoint?

Thanks again

**Comment by bedapudi6788** [comment]
can you run ```pip show txt2txt``` and paste the output here.

**Comment by zhushaojin** [comment]
Thanks for the replay. The output of `pip show txt2txt` is

Name: txt2txt
Version: 1.1.1
Summary: Out of the Box, Easy to use sequence to sequence library with attention for text.
Home-page: https://github.com/bedapudi6788/txt2txt
Author: BEDAPUDI PRANEETH
Author-email: praneethbedapudi@gmail.com
License: GPLv3
Location: /anaconda3/envs/python36/lib/python3.6/site-packages
Requires: numpy, keras
Required-by:

**Comment by bedapudi6788** [comment]
ah, there is the issue. DeepCorrect is based on an older version of https://github.com/bedapudi6788/txt2txt/ 

Just run ```pip install txt2txt==1.0.9``` and it should work.

**Comment by zhushaojin** [comment]
It sure did work! Thanks a lot!
But there are still some problem of accuracy.
In my code 

---------------------------------
 import sys
from deepsegment import DeepSegment
from deepcorrect import DeepCorrect

input_string = sys.argv[1]

segmenter = DeepSegment('en')
seg_string = segmenter.segment(input_string)

corrector = DeepCorrect('./models/deeppunct_params_en', "./models/deeppunct_checkpoint_g    oogle_news")

punct_list = []
for item in seg_string:
    this_punct = corrector.correct(item)
    punct_list.append(this_punct[0]["sequence"])

print(seg_strinig)
output_string = ' '.join(punct_list)
print(output_string)

-----------------------------------

My output is
['Why you did this to me I hate you', 'you are dead to me']
Why you did this to me I hate you? You are dead to me.

The output of demo is:
"Why you did this to me? I hate you, You are dead to me."

It may be the issue of DeepSegment?  I used the params and checkpoint auto-download by the DeepSeg code

**Comment by bedapudi6788** [comment]
oh, i will check this and get back to you. I am re-opening the issue meanwhile.

**Comment by zhushaojin** [comment]
Thank you ;)

**Comment by dKard** [comment]
Do you have a google colab for this it would make things easier?

**Comment by Virmli** [comment]
Hey guys, do we have updates on how to solve accuracy problem between demo and local code? I believe I have same issue as @zhushaojin Thank you @bedapudi6788

**Comment by bedapudi6788** [comment]
Hi All, the demo hosted, now uses a completely different architecture (~100x faster than deepcorrect). I might not be able to open-source it, as I developed it in a professional capacity. I am figuring out a way to open source it and will update here when I do so.

**Comment by Virmli** [comment]
Thank you @bedapudi6788  for update!

**Comment by bedapudi6788** [comment]
we are working on a faster and more accurate punctuation correction at https://github.com/notAI-tech/fastpunct .

The core idea is similar (seq2seq), but @harikodali figured out a way to make the decoding faster. This repo is expected to be released by the end of this month.
